### ISSUE TITLE
把mpvue-echarts写成组件后，同一个页面使用多次只有第一个显示

### ISSUE THREAD

**Issue by SmithBox** [F-loat/mpvue-echarts#10]
把mpvue-echarts写成组件后，同一个页面使用多次只有第一个显示，会报错。
Do not have handler in current page: pages/flowDetail/main. Please make sure that handler has been defined in pages/flowDetail/main, or not use handler with 'v-if'
![_20180524154456](https://user-images.githubusercontent.com/20665779/40471517-82944870-5f69-11e8-876c-8f32b7a2e4d8.png)

**Comment by F-loat** [comment]
不同的 canvas 要指定不同的 id

**Comment by SmithBox** [comment]
![image](https://user-images.githubusercontent.com/20665779/40472036-ebef776c-5f6a-11e8-9961-1192aee2fc52.png)
这样写的id，还是同样的报错。大神秒回复，好感动

**Comment by SmithBox** [comment]
![image](https://user-images.githubusercontent.com/20665779/40472750-e84ada82-5f6c-11e8-8422-35a9831ba30f.png)
不好意思，一着急把canvasId写成id了，谢谢大神

**Comment by liyuan900226** [comment]
你这个问题解决了吗？我也碰到了，该怎么解决啊？

**Comment by liyuan900226** [comment]
老哥怎么解决的啊，我们项目里的页面图表都是动态配置的，只能用组件去渲染
