### ISSUE TITLE
同一页面使用多次组件，script中声明的option在三个组件是同一个

### ISSUE THREAD

**Issue by SmithBox** [F-loat/mpvue-echarts#11]
我这边把echarts写成了一个组件，在一个页面中使用了三次，这三个组件里的option是同一个了，导致样式完全相同。我把mpvue-echarts所需要的option和initchart方法写到了vue 的data里，结果报错了，还看不懂。。。
![image](https://user-images.githubusercontent.com/20665779/40541863-2b994f6a-6050-11e8-8620-ea9869d8b93c.png)
![image](https://user-images.githubusercontent.com/20665779/40541960-9abb80e8-6050-11e8-9dff-87b493e158f7.png)
![image](https://user-images.githubusercontent.com/20665779/40541980-ad568e64-6050-11e8-8ee5-5634f0ba93c0.png)
第二种赋值，同样的报错
![image](https://user-images.githubusercontent.com/20665779/40541995-b86433ce-6050-11e8-97e5-7da09d493aa0.png)

**Comment by F-loat** [comment]
注意不要把 chart 实际赋值到 this 上

**Comment by SmithBox** [comment]
multiCharts这个示例看了的，可是那个是在一个页面写了两个方法所以有两个option，我在组件里这样写就没组件的意义了。可以解释下这个报错是什么吗

**Comment by F-loat** [comment]
this.chart = 
这句导致的错误，大概是 chart 实例里有很多循环引用，不赋值到 this 上就行

**Comment by SmithBox** [comment]
嗯嗯，多谢啦

**Comment by SmithBox** [comment]
感觉这样写不了组件了，一个页面有三个图表，就得写三遍了。溜了溜了

**Comment by F-loat** [comment]
不是啊，你把 chart 直接定义在 script 里就行

**Comment by F-loat** [comment]
``` js
<script>
import * as echarts from 'echarts'
import mpvueEcharts from 'mpvue-echarts'
let chart

export default {
...
}
```

**Comment by SmithBox** [comment]
不是，是组件里在script声明的option会在同一个页面共用了。我现在解决了，把option写在data里。
![image](https://user-images.githubusercontent.com/20665779/40544486-0f41a960-605b-11e8-8c33-43deacf3d394.png)chart里这样取option，同一页面的三个组件取的就是各自的option了

**Comment by SmithBox** [comment]
![image](https://user-images.githubusercontent.com/20665779/40544705-d1825e84-605b-11e8-93ab-7ff47e7a944d.png)
![image](https://user-images.githubusercontent.com/20665779/40544715-dad2c154-605b-11e8-9599-1dde7752128b.png)
我发现这个方法也必须写script里，不然也会报错
其他都按照文档写，option写data里，才能写成组件了

**Comment by F-loat** [comment]
option 不应该用 prop 传进去吗

**Comment by F-loat** [comment]
onInit 这些函数应该写在 methods 里也可以

**Comment by SmithBox** [comment]
我这个项目的option是基本一样，只是换了颜色，数据和数据对应的名称都是后台传了，所以就没用prop

**Comment by F-loat** [comment]
不清楚你怎么写的，完全可以像下面这样，把 chart 定义在函数内部，多个组件间的数据也应该不会冲突的，具体的你多尝试下吧

``` js
function (canvas, width, height) {
  const chart = echarts.init(canvas, null, {
    width: width,
    height: height
  })
  canvas.setChart(chart)
  chart.setOption(this.options())
},
```

**Comment by SmithBox** [comment]
确实是我之前写错了，现在我这边组件写好。
按照你的方法试了下，不报错了，是我之前给onInit赋值的方式错了才会报错，基础不好，麻烦大神啦
![image](https://user-images.githubusercontent.com/20665779/40548034-23e267fa-6066-11e8-855b-61a43ec8464a.png)

**Comment by SmithBox** [comment]
退出页面再进页面，这个页面data里的数据和页面退出之前是一样的，是这样的吗，页面其实没卸载

**Comment by F-loat** [comment]
嗯，mpvue 目前就是这样的，具体看这个：https://github.com/Meituan-Dianping/mpvue/issues/140

**Comment by SmithBox** [comment]
嗯嗯，谢谢啦。再写的时候注意下

**Comment by CookieCoffee** [comment]
楼主 请问你是怎么从父组件传值得。父组件异步获取的数据如何动态修改？子组件才可以重弄新渲染
