### ISSUE TITLE
怎么样在mounted中获取后台数据后修改option中的值

### ISSUE THREAD

**Issue by bumandpunk** [F-loat/mpvue-echarts#13]
先把echarts设置为懒加载获取到数据之后怎么样把数据传进去 -

**Comment by chunmu** [comment]
不行诶 是不是要再次调用setoption

**Comment by F-loat** [comment]
@chunmu 不行具体是有什么问题，setOption 应该也可以吧，但是也是要先手动调用下 init 方法的吧

**Comment by F-loat** [comment]
参考这个文件看下吧 https://github.com/F-loat/mpvue-echarts/blob/master/examples/lazyLoad.vue

**Comment by F-loat** [comment]
第一次初始化后，直接调用 `chart.setOption` 应该也是可以的
