### ISSUE TITLE
一个页面多个懒加载实例，只能显示一个

### ISSUE THREAD

**Issue by WwJoyous** [F-loat/mpvue-echarts#16]
一个页面多个懒加载实例，只能显示一个是怎么回事尼。跟普通的一个页面多个实例写法是一样的么

**Comment by F-loat** [comment]
一样的吧，你 canvasId 设置了没

**Comment by WwJoyous** [comment]
懒加载的demo中不是没有canvasId嘛，是通过ref来init的嘛

**Comment by F-loat** [comment]
多个图表需要设置不同的 canvasId，这是小程序本身的限制

**Comment by WwJoyous** [comment]
谢谢博主，是这个问题加上canvasId就可以了，我以为ref不同就可以了标识
