### ISSUE TITLE
npm i mpvue-charts 后报依赖错误

### ISSUE THREAD

**Issue by kaven85** [F-loat/mpvue-echarts#2]
![wx20180320-135744](https://user-images.githubusercontent.com/2148307/37638221-b1be849a-2c46-11e8-8f56-081a9303ea7c.png)
能给个完整列子吗？

**Comment by F-loat** [comment]
完整示例：https://github.com/F-loat/mpvue-examples/tree/mpvue-echarts/mpvue-echarts

**Comment by restran** [comment]
一共要安装这几个依赖才行

```
echarts
mpvue-echarts
less
less-loader
```

**Comment by F-loat** [comment]
嗯。。less 是没必要的，我之后去除下

**Comment by F-loat** [comment]
less 已经移除了，echarts 本身是 mpvue-echarts 的依赖项，应该会自动安装，不过为了避免 eslint 的错误提示，也可以再安装一次
