### ISSUE TITLE
编译完成后代码包超过2M，无法上传

### ISSUE THREAD

**Issue by shobal2018** [F-loat/mpvue-echarts#20]

**Comment by F-loat** [comment]
下载自定义版本的 echarts 可以减小一些体积

**Comment by F-loat** [comment]
也可以试下分包处理 https://github.com/F-loat/mpvue-quickstart

**Comment by shobal2018** [comment]
感谢回复，我试下引入自定义echarts，但是分包不好使，我分包只有一个地图的页面编译出来都有3M多

Best Regrads
Shobal

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 柴茂源 <notifications@github.com>
发送时间: Thursday, July 5, 2018 10:47:46 PM
收件人: F-loat/mpvue-echarts
抄送: shobal2018; Author
主题: Re: [F-loat/mpvue-echarts] 编译完成后代码包超过2M，无法上传 (#20)


也可以试下分包处理 https://github.com/F-loat/mpvue-quickstart

―

**Comment by F-loat** [comment]
呃，分包的效果不会比不分差的，不过被引用的次数多的话，可能还是在主包里

**Comment by shobal2018** [comment]
您好，方便我加一下您的微信么？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 柴茂源 <notifications@github.com>
发送时间: Thursday, July 5, 2018 11:12:49 PM
收件人: F-loat/mpvue-echarts
抄送: shobal2018; Author
主题: Re: [F-loat/mpvue-echarts] 编译完成后代码包超过2M，无法上传 (#20)


呃，分包的效果不会比不分差的，不过被引用的次数多的话，可能还是在主包里

―

**Comment by F-loat** [comment]
只是这个问题的话，直接在 issue 里问吧，也方便其他人参考

**Comment by shobal2018** [comment]
![tim 20180706102017](https://user-images.githubusercontent.com/40852517/42356702-8ae0bf40-8106-11e8-825d-de4c35d6f29b.png)
![_20180706101714](https://user-images.githubusercontent.com/40852517/42356703-8bf9d286-8106-11e8-8d53-805a8dc5a368.png)
![_20180706102134](https://user-images.githubusercontent.com/40852517/42356704-8c4fc056-8106-11e8-9a6c-3f173f097ff3.png)
按照您的建议，我做了两次尝试。首先，在分包里只放了一个页面，然而依然提示我分包大小超限，然后将echarts换成官网自定义的echarts.js，编译报错。

**Comment by F-loat** [comment]
build 之后应该不会这么大啊，自定义你看下已有的 issue 把，应该没问题的
