### ISSUE TITLE
关于多个图表适配问题

### ISSUE THREAD

**Issue by duanmuyuan** [F-loat/mpvue-echarts#21]
如果多个图表在一个页面
那么那个width 和 height 只会获取第一个的宽和高  
对于这个你怎么看的~ ~

**Comment by F-loat** [comment]
没太懂，具体说下？不同的 canvas 需要指定不同的 id

**Comment by duanmuyuan** [comment]
query.select('.ec-canvas').boundingClientRect((res) => {
        if (!res) {
          setTimeout(() => this.init(), 50);
          return;
        }
        this.chart = this.onInit(canvas, res.width, res.height);
      }).exec();

就是这里你获取的是.ec-canvas 节点的宽和高  但是结果会是所有的 canvas都叫这个类名  所以就会只获取第一个的值

**Comment by duanmuyuan** [comment]
代码我修改了  但是你这个不让我提交  所以我贴给你
  <canvas
    v-if="canvasId"
    class="ec-canvas"
    :id="canvasId"
    :canvasId="canvasId"
    @touchstart="touchStart"
    @touchmove="touchMove"
    @touchend="touchEnd"
    @error="error">
  </canvas>

      query.select(`#${canvasId}`).boundingClientRect((res) => {
        if (!res) {
          setTimeout(() => this.init(), 50);
          return;
        }
        this.chart = this.onInit(canvas, res.width, res.height);
      }).exec();

**Comment by F-loat** [comment]
嗯，我晚点看下，可能原本那个库没这个问题

**Comment by duanmuyuan** [comment]
我修改了  代码也提了

**Comment by duanmuyuan** [comment]
我修改了 代码提了  你合并过来就可以了

**Comment by F-loat** [comment]
v0.2.7
