### ISSUE TITLE
显示Template not found.

### ISSUE THREAD

**Issue by maggie-chen** [F-loat/mpvue-echarts#23]
`Template "334c8922" not found.
<template name="6224ccf9">
<view class="_div data-v-68efa517 echarts-wrap">
<template canvasId="demo-canvas" data="{{...$root[$kk+'0'], $root}}" is="334c8922"></template>
 </view>
</template>`

**Comment by F-loat** [comment]
应该是 mpvue-loader 的版本和打包配置不匹配的问题，https://github.com/Meituan-Dianping/mpvue/issues/795
