### ISSUE TITLE
提示vendor.js过大

### ISSUE THREAD

**Issue by zyqq** [F-loat/mpvue-echarts#27]
安装完echarts后小程序代码包超过2048kb了怎么办

**Comment by F-loat** [comment]
看下已有 issue，谢谢

**Comment by zyqq** [comment]
注释掉 import echarts from "echarts";然后按需引入即可解决问题
`// import echarts from "echarts";
import mpvueEcharts from "mpvue-echarts";

// 引入 ECharts 主模块
var echarts = require('echarts/lib/echarts');
// 引入柱状图
require('echarts/lib/chart/bar');
// 引入提示框和标题组件
require('echarts/lib/component/tooltip');`

**Comment by 1102568869** [comment]
另外 真正上传的时候 使用npm run build打包压缩版本, 不要用npm run dev的未压缩版本

**Comment by circlewang** [comment]
我的echarts压缩定制后有三百多，但是总体vendor打包完后还要540k，有什么方法能拆包或者压缩吗
