### ISSUE TITLE
嵌套饼图点击后样式出错

### ISSUE THREAD

**Issue by zyqq** [F-loat/mpvue-echarts#28]
![_20180802161452](https://user-images.githubusercontent.com/15664576/43571348-52d7bf12-966f-11e8-8e8c-0cc027457c59.png)
![_20180802161456](https://user-images.githubusercontent.com/15664576/43571350-530ff9ea-966f-11e8-9a44-f575e2e85978.png)

**Comment by F-loat** [comment]
这种错误建议去 echarts 官方反馈
