### ISSUE TITLE
安装玩echarts后，打包上传发现超出2m的限制

### ISSUE THREAD

**Issue by lingchuanzhou** [F-loat/mpvue-echarts#29]
安装玩echarts后，打包上传发现超出2m的限制，请问作者是如何解决的？分包吗

**Comment by lingchuanzhou** [comment]
安装完echarts后，打包上传发现超出2m的限制，请问作者是如何解决的？分包吗

**Comment by F-loat** [comment]
这个问题 issue 里起码有四五个了。。
