### ISSUE TITLE
打包预览时体积超过2M

### ISSUE THREAD

**Issue by EngMJ** [F-loat/mpvue-echarts#3]
在安装完vue-echarts后,按照提示我安装echarts,.
 improt了echarts.  图表显示都正常,就是体积超过2M无法预览.

**Comment by F-loat** [comment]
可以参考这个 pr 更新下压缩插件 [mpvue-quickstart#18](https://github.com/mpvue/mpvue-quickstart/pull/18)，另外 [echarts](http://echarts.baidu.com/download.html) 官网可以定制轻量版
