### ISSUE TITLE
mpvue引入这个库需要进行babel转换吗？

### ISSUE THREAD

**Issue by syyzz3** [F-loat/mpvue-echarts#35]
在mpvue官网看说mpvuejs loader默认不babel处理node_modules内的包，会在低版本的手机报错？
这个库会不会有影响？
echras 和 mpvue-ehcars需不需要用babel转换一下？
> "dependencies": {
"echarts": "^4.1.0",
"flyio": "^0.6.0",
"mpvue": "^1.0.11",
"mpvue-echarts": "^0.2.7",
"vuex": "^3.0.1"
},

**Comment by F-loat** [comment]
readme 里有说明，注意看下，开发工具开 es6 转换也可以

**Comment by syyzz3** [comment]
@F-loat 引入的eacrhs需要babel吗？
开发工具开启“es6 转 es5” 会对run build之后的代码 再次转换？

**Comment by F-loat** [comment]
echarts 一般使用的都是转换后的版本了，build 后 500kb 内的文件都会转换的

**Comment by syyzz3** [comment]
@F-loat  非常感谢
