### ISSUE TITLE
不能自定义主题吗？

### ISSUE THREAD

**Issue by ai116458960** [F-loat/mpvue-echarts#36]
如题
如果需要改变图标的样式 怎么处理 望大神指点一哈 感谢感谢

**Comment by F-loat** [comment]
此类问题建议到官方仓库进行咨询 [echarts-for-weixin](https://github.com/ecomfe/echarts-for-weixin/issues)

**Comment by F-loat** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/266
