### ISSUE TITLE
请问手指在图表上滑动时，滑动到边界时会造成白屏的现象，应该如何处理呢？

### ISSUE THREAD

**Issue by smallsun0122** [F-loat/mpvue-echarts#42]
图表是自适应平铺整个屏幕的，手指移动到边界时，会有白屏现象，重现点击屏幕才会复现图表
![v6vhs-l9la9](https://user-images.githubusercontent.com/22772199/48177544-17bdbe80-e350-11e8-9aa6-3c31a5e4c11b.gif)

**Comment by F-loat** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/331

**Comment by smallsun0122** [comment]
好的~ 非常感谢🙏
