### ISSUE TITLE
xAxis配置项axisPointer中设置富文本样式无效

### ISSUE THREAD

**Issue by smallsun0122** [F-loat/mpvue-echarts#46]
![image](https://user-images.githubusercontent.com/22772199/48400490-71aff100-e761-11e8-9462-6afc33ec7c88.png)
如图，对这两行字体分别定义不同的样式和大小，但是富文本识别不了。

` xAxis: {
          show: false,
          position: 'top',
          data: _this.dateList,
          axisPointer: {
            show: true,
            type: 'line',
            padding: [10, 0],
            label: {
              color: '#2b3038',
              backgroundColor: '#fff',
              shadowColor: '#fff',
              formatter: function (params) {
                return '{data|' + params.seriesData[0].value.toFixed(4) + '}{time|' + '\n' + params.value + '}'
              },
              rich: {
                data: {
                  color: '#2b3038',
                  fontSize: 16
                },
                time: {
                  color: '#b2b5b7',
                  fontSize: 10
                }
              },
              lineHeight: 56
            },
            lineStyle: {
              color: '#CBD0D6',
              type: 'dotted',
              height: '243px'
            }
          }
        }`

**Comment by F-loat** [comment]
看下这个 https://github.com/ecomfe/echarts-for-weixin/issues/344

**Comment by smallsun0122** [comment]
是支持富文本，但是富文本设置样式无效呀？

**Comment by F-loat** [comment]
这类问题在[官方仓库](https://github.com/ecomfe/echarts-for-weixin)反馈吧
