### ISSUE TITLE
为什么例子中的图表的 legend 除散点图外 几乎都不能显示？

### ISSUE THREAD

**Issue by sogoodgithub** [F-loat/mpvue-echarts#47]

**Comment by SmithBox** [comment]
你设置legend的位置了吗，还有legend一定要跟series里的name对应上。我这里正常显示
      legend: {
        left: '7.5',
        data: [
          { name: '老客户', icon: 'circle' },
          { name: '新客户', icon: 'circle' }
        ]
      },
      series: [
        {
          name: '老客户',
          type: 'line',
          symbol: 'none',
          data: [0, 0, 0, 0, 0, 0, 0]
        },
        {
          name: '新客户',
          type: 'line',
          symbol: 'none',
          data: [0, 0, 0, 0, 0, 0, 0]
        }
      ]

**Comment by Virczz** [comment]
emmm。经过我测试并翻看文档，发现legend不显示的原因，和引用的echart完整度有关。精简版echart.simple.js，不会展示legend。而echart.common.js和完整版，均可以展示。

**Comment by Zillionnn** [comment]
> emmm。经过我测试并翻看文档，发现legend不显示的原因，和引用的echart完整度有关。精简版echart.simple.js，不会展示legend。而echart.common.js和完整版，均可以展示。

+1
