### ISSUE TITLE
ECharts绑定事件没有响应

### ISSUE THREAD

**Issue by dongsuo** [F-loat/mpvue-echarts#5]
获取chart实例后，绑定事件，但是 ECharts 没有给出响应
代码：
`setTimeout(() => {
      console.log('echarts ', chart)
      chart.on('mouseDown', function (params) {
        console.log('mouseDown' + params)
      })
    }, 2000)`
看log可以看到事件绑定是成功了的：
![image](https://user-images.githubusercontent.com/15919955/38966834-bdc071ae-43b6-11e8-8b09-1badcbea1076.png)

echarts-for-weixin 官方代码中，事件是有响应的，猜测是否是 mpvue 的事件机制的问题？

**Comment by F-loat** [comment]
你是想实现什么效果呢，默认已经绑定了三个触摸事件，你可以参考下源码的绑定方式

**Comment by dongsuo** [comment]
我想要获取用户点击的数据内容，如官网实例：
http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA

我刚刚又重新试了一下，发现在部分图中是可以正常响应的，我再仔细看看吧，抱歉打扰了。
