### ISSUE TITLE
如何循环渲染多个不同option的图表

### ISSUE THREAD

**Issue by supercat1995** [F-loat/mpvue-echarts#50]
如何循环渲染多个不同option的图表
例如
bar1数据为[820, 932, 901, 934, 1290, 1330, 1320]，
bar2数据为[1820, 1932, 3901, 5934, 31290, 1330, 1320]
bar3数据为[2820, 2932, 4901, 6934, 11290, 1330, 1320]
要在页面渲染40个，这种要怎么解决

**Comment by F-loat** [comment]
40 个图表小程序会卡死的吧。。建议修改交互逻辑，至于循环应该和普通组件没区别，提供唯一 id 就行
