### ISSUE TITLE
使用markLine无效

### ISSUE THREAD

**Issue by myhuangqiang** [F-loat/mpvue-echarts#54]
无任何报错，在网页中能正常显示辅助线，小程序中不显示
![image](https://user-images.githubusercontent.com/25660665/53070486-50a62b80-351a-11e9-9fd8-6f10e05c1369.png)

**Comment by myhuangqiang** [comment]
sorry，傻逼了，自己定制的没有选择markLine组件

**Comment by F-loat** [comment]
那应该没问题了吧
