### ISSUE TITLE
动态绑定数据失败

### ISSUE THREAD

**Issue by zhaixiyun** [F-loat/mpvue-echarts#56]
有没有关于动态绑定数据的示例，看到有个懒加载的示例网址已经进不去了

**Comment by F-loat** [comment]
懒加载的链接没问题啊 https://github.com/F-loat/mpvue-echarts/blob/master/examples/src/pages/demos/lazyLoad.vue

**Comment by zhaixiyun** [comment]
嗯，多谢，看到了已经
