### ISSUE TITLE
Typescript环境下声明文件

### ISSUE THREAD

**Issue by pantt** [F-loat/mpvue-echarts#57]
安装完包之后，用Typescript语言写的，提示找不到module！
请问是缺少ts声明文件吗？有mpvue-echarts的声明文件吗？
求各位大大告知一下，js没问题，但是ts就有问题
![e rtxt9 g ec6yeuh2 ov7p](https://user-images.githubusercontent.com/44255498/53945112-d2da4680-40fb-11e9-9c52-35311232d0a6.png)

![br3x c vd 2dxg oct 8r](https://user-images.githubusercontent.com/44255498/53945119-d8379100-40fb-11e9-97a9-60ac8c8270f5.png)

**Comment by F-loat** [comment]
v0.3.1
