### ISSUE TITLE
请问如何替换定制的echarts.mini.js?

### ISSUE THREAD

**Issue by yunyingchen** [F-loat/mpvue-echarts#58]
vendor.js体积过大，超过500kb。我看了历史的提问，只是说自己定制，请问定制后，如何应用自己的定制文件？

**Comment by F-loat** [comment]
直接 import 定制后的文件就行

**Comment by yunyingchen** [comment]
好的，我明天试试，多谢




| |
chen2y7
邮箱：chen2y7@163.com
|

Signature is customized by Netease Mail Master

在2019年03月13日 19:23，柴茂源 写道：

直接 import 定制后的文件就行

**Comment by yunyingchen** [comment]
你好，我把定制后的文件（包含折线图、柱状图、直角坐标系、标题、图例提示框）放在static目录下，直接import相对路径，目前体积暂时缩小了，多谢！

**Comment by F-loat** [comment]
放在 src 目录里就行，static 里的会被多复制一份的

**Comment by yunyingchen** [comment]
你好，我在src目录下新建了一个echarts目录，下面存放我自定义的文件，echarts.min.js。
然后 
import echarts from '../../echarts/echarts.min.js'
import mpvueEcharts from 'mpvue-echarts'

控制台报错如下：
 warning  in ./src/pages/chart/chart.vue

14:10-17 "export 'default' (imported as 'echarts') was not found in '../../echarts/echarts.min.js'

请问我应该如何正确引入？你好，我在src目录下新建了一个echarts目录，下面存放我自定义的文件，echarts.min.js。
然后 
import echarts from '../../echarts/echarts.min.js'
import mpvueEcharts from 'mpvue-echarts'

控制台报错如下：
 warning  in ./src/pages/chart/chart.vue

14:10-17 "export 'default' (imported as 'echarts') was not found in '../../echarts/echarts.min.js'

请问我应该如何正确引入？

**Comment by yunyingchen** [comment]
你好，我在src目录下新建了一个echarts目录，下面存放我自定义的文件，echarts.min.js。
然后
import echarts from '../../echarts/echarts.min.js'
import mpvueEcharts from 'mpvue-echarts'

控制台报错如下：
warning in ./src/pages/chart/chart.vue

14:10-17 "export 'default' (imported as 'echarts') was not found in '../../echarts/echarts.min.js'

请问我应该如何正确引入？

**Comment by F-loat** [comment]
这样试下

``` js
import * as echarts from '../../echarts/echarts.min.js'
```

**Comment by yunyingchen** [comment]
这个方法我试过了，报错如下：
 WARNING  Compiled with 1 warnings                                                                              11:59:17

 warning  in ./src/pages/chart/chart.vue

15:10-22 "export 'init' (imported as 'echarts') was not found in '../../echarts/echarts.min.js'

**Comment by F-loat** [comment]
下个不压缩的版本呢

**Comment by F-loat** [comment]
定制后的下载链接发一个看看

**Comment by yunyingchen** [comment]
不压缩的版本还是会占用内存呀，我是直接在echarts父母定制化界面选择需要的组件下的，我觉得应该和文件本身没关系。




| |
chen2y7
邮箱：chen2y7@163.com
|

Signature is customized by Netease Mail Master

在2019年03月14日 12:02，柴茂源 写道：

定制后的下载链接发一个看看

**Comment by F-loat** [comment]
你用到的图表类型可以直接安装 echarts 后引用这个文件

``` js
import * as echarts from 'echarts/dist/echarts.simple.min'
```

src 目录里得配置下 webpack，忽略掉这个文件，压缩后的文件看来放在 static 目录中就行

``` js
{
  test: /\.js$/,
  exclude: resolve('src/echarts.min.js'),
  ...
}
```

**Comment by yunyingchen** [comment]
方便加个微信吗？截图比较清晰一点。




| |
chen2y7
邮箱：chen2y7@163.com
|

Signature is customized by Netease Mail Master

在2019年03月14日 12:23，柴茂源 写道：

你用到的图表类型可以直接安装 echarts 后引用这个文件

import*asechartsfrom'echarts/dist/echarts.simple.min'

src 目录里得配置下 webpack，忽略掉这个文件，压缩后的文件看来放在 static 目录中就行

{

  test:/\.js$/,

  exclude:resolve('src/echarts.min.js'),

  ...

}

**Comment by F-loat** [comment]
放在 static 里没问题的话，就放 static 目录就行，static 目录里的应该不会被打包到 bundle 里，只会复制一份

**Comment by yunyingchen** [comment]
好的，我下午再试试刚刚说的方法，谢谢




| |
chen2y7
邮箱：chen2y7@163.com
|

Signature is customized by Netease Mail Master

在2019年03月14日 12:26，柴茂源 写道：

放在 static 里没问题的话，就放 static 目录就行，static 目录里的应该不会被打包到 bundle 里，只会复制一份

**Comment by yunyingchen** [comment]
刚刚你说的方法我试过了，使用echarts.simple.min打包编译后的内存为732kb（已移除static里的echarts.min.js），放在static的自定义文件为889kb。 目前暂时可用，多谢！
