### ISSUE TITLE
我再官网直接下载2.0和3.0的echarts.common.min.js 无法使用

### ISSUE THREAD

**Issue by goodbuildwhc** [F-loat/mpvue-echarts#60]
报错
![image](https://user-images.githubusercontent.com/14182591/54753412-f503b680-4c1b-11e9-8fcb-096bda9eaf31.png)

**Comment by nealHong** [comment]
web需要单独处理，用条件编译

**Comment by F-loat** [comment]
echarts 用 4.0 以上版本试试，旧版可能没做多端兼容处理
