### ISSUE TITLE
echarts-for-weixin 中的层级问题在mpvue中如何处理？

### ISSUE THREAD

**Issue by johnnynode** [F-loat/mpvue-echarts#61]
相关issue:

- https://github.com/ecomfe/echarts-for-weixin/issues/459 
- https://github.com/ecomfe/echarts-for-weixin/issues/349
- https://github.com/ecomfe/echarts-for-weixin/issues/84
- https://github.com/ecomfe/echarts-for-weixin/issues/237

问：这里的 ` cover-view` 应如何应用

根据官方文档：
https://developers.weixin.qq.com/miniprogram/dev/component/cover-view.html

这里设置了：
```html
<cover-view class="echarts-wrap">
    <mpvue-echarts :echarts="echarts" :onInit="initChart" :throttleTouch="true" :canvasId="`r${'canvasId' + i + k }`" />
</cover-view> 
```

微信开发者工具正常：
![image](https://user-images.githubusercontent.com/12521566/55458990-fe7c1e00-5620-11e9-841b-060ede7cfa65.png)

真机不正常：iOS:
![image](https://user-images.githubusercontent.com/12521566/55459080-36836100-5621-11e9-9953-f200bb784ca0.png)

iOS 版本：
12.1.4（16D57）
微信版本：
7.0.3

**Comment by johnnynode** [comment]
已解决：

使用 `cover-view` 组件包裹搜索框，而非 echarts组件 😅 ~

**Comment by johnnynode** [comment]
但是又有一个问题：

cover-view 只支持嵌套cover-view、cover-image，对于 mpvue-weui中的 `mp-searchbar` 组件，需要自己实现

![image](https://user-images.githubusercontent.com/12521566/55461002-f5418000-5625-11e9-8115-04048f7b15d3.png)

**Comment by mihuartuanr** [comment]
所以呢…看了一圈了快，什么办法解决呢
