### ISSUE TITLE
自定义构建 ECharts导入后运行出错。

### ISSUE THREAD

**Issue by novasq** [F-loat/mpvue-echarts#7]
import * as echarts from '../../echarts.min.js'
    import mpvueEcharts from 'mpvue-echarts'
.
.
.
错误信息：
thirdScriptError
this.echarts.setCanvasCreator is not a function;at pages/one/main page lifeCycleMethod onReady function
TypeError: this.echarts.setCanvasCreator is not a function

**Comment by F-loat** [comment]
试了下仪表盘也没问题的啊，你用的 mpvue-echarts 是最新版的不

**Comment by F-loat** [comment]
我下的这个 http://echarts.baidu.com/builder/echarts.html?charts=gauge&components=title,legendScroll&api=true&version=4&versionCode=4.0.4

**Comment by novasq** [comment]
mpvue-echarts  "version": "0.2.2"

**Comment by F-loat** [comment]
你参考下 https://github.com/F-loat/mpvue-echarts/blob/example/src/pages/demos/gauge.vue

**Comment by novasq** [comment]
好的，非常感谢！

**Comment by markzhan** [comment]
http://echarts.baidu.com/download.html 下载精简版

  "dependencies": {
    "echarts": "^4.0.4",
    "mpvue": "^1.0.10",
    "mpvue-echarts": "^0.2.2",
    "vuex": "^2.3.1"
  },

import * as echarts from '@/libs/echarts.simple.min'
import mpvueEcharts from 'mpvue-echarts'

同样出错：
thirdScriptError
this.echarts.setCanvasCreator is not a function;at pages/result/main page lifeCycleMethod onReady function
TypeError: this.echarts.setCanvasCreator is not a function

**Comment by F-loat** [comment]
反馈时请附上下载链接，另外最好对比下和下面这个的差异 http://echarts.baidu.com/builder/echarts.html?charts=gauge&components=title,legendScroll&api=true&version=4&versionCode=4.0.4

**Comment by markzhan** [comment]
参考example：mpvue-echarts/build/webpack.base.conf.js
修改 build\webpack.base.conf.js
test: /\.js$/,
include: [resolve('src'), resolve('test')],
新增：
exclude: [resolve('src/libs')],
