### ISSUE TITLE
饼图报错_this2.chart.getZr is not a function

### ISSUE THREAD

**Issue by webVictor** [F-loat/mpvue-echarts#70]
_this2.chart.getZr is not a function;at SelectorQuery callback function
TypeError: _this2.chart.getZr is not a function

**Comment by F-loat** [comment]
echarts 是哪个版本？

**Comment by webVictor** [comment]
> echarts 是哪个版本？
"echarts": "^4.0.4",版本"version": "4.3.0"
"mpvue-echarts": "^0.3.1",

**Comment by webVictor** [comment]
> echarts 是哪个版本？

echarts 是哪个版本？
"echarts": "^4.0.4",版本"version": "4.3.0"
"mpvue-echarts": "^0.3.1",

**Comment by F-loat** [comment]
使用 onInit 属性传入 init 函数，init 事件的用法有问题

**Comment by webVictor** [comment]
> 使用 onInit 属性传入 init 函数，init 事件的用法有问题
谢谢哈

**Comment by F-loat** [comment]
没事的，示例也更新了下
