### ISSUE TITLE
使用定制的echarts.min.js，import后整个文件打包进了页面的js中

### ISSUE THREAD

**Issue by KePingHub** [F-loat/mpvue-echarts#74]
![image](https://user-images.githubusercontent.com/28534235/67733637-e98e2e80-fa39-11e9-91ef-e2c757d7a389.png)
![image](https://user-images.githubusercontent.com/28534235/67733759-3114ba80-fa3a-11e9-932f-a35ff95ec3a1.png)
![image](https://user-images.githubusercontent.com/28534235/67733783-3e31a980-fa3a-11e9-9585-a94a251cf68b.png)

**Comment by F-loat** [comment]
这个是正常的吧
