### ISSUE TITLE
请问“mpvue-echarts”满足做疫情地图（国内外）、折线图、表格的需求吗

### ISSUE THREAD

**Issue by xmt1997** [F-loat/mpvue-echarts#83]
**用mpvue+云开发 微信小程序开发
做最近的疫情地图和疫情趋势、表格数据等，
是否可以引入“mpvue-echarts”，满足以上需求？
谢谢！**

**Comment by F-loat** [comment]
echarts 支持的图表，小程序里应该都支持了的，可能会有的问题参见 issue 列表
