### ISSUE TITLE
关于本例子npm run build 之后dist目录中没有pages文件夹生成的问题

### ISSUE THREAD

**Issue by naoxiaozhi** [F-loat/mpvue-echarts#9]
关于mpvue-echarts-example~
<img width="606" alt="2018-05-18 7 32 56" src="https://user-images.githubusercontent.com/21259996/40208928-f48955ba-5a6e-11e8-8bf3-665c2fa8511b.png">
按步骤运行之后，在开发者工具中报错如图片展示，查找发现build之后的dist目录比微信小程序的目录少了pages文件夹导致找不到pages/index，初入坑，求解答～

**Comment by F-loat** [comment]
同步下最新的试试，打包时没有报错吗？

**Comment by naoxiaozhi** [comment]
同步了最新版，可以啦～
